# Generated by Django 2.1.2 on 2018-11-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWeb', '0004_auto_20181025_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Perro',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
